[package]
name = "kiss3d-trackball"
version = "0.3.0"
authors = ["Rouven Spreckels <rs@qu1x.dev>"]
edition = "2018"
description = "Virtual Trackball Camera Mode for Kiss3D"
documentation = "https://doc.qu1x.dev/kiss3d-trackball"
repository = "https://github.com/qu1x/kiss3d-trackball"
readme = "README.md"
license = "BSD-2-Clause-Patent"
keywords = [
	"virtual-trackball",
	"exponential-map",
	"quaternion",
	"arcball",
	"camera",
]
categories = [
	"graphics",
]
include = [
	"src/**/*.rs",
	"Cargo.toml",
	"README.md",
	"RELEASES.md",
	"LICENSES/*.md",
]

[badges]
travis-ci = { repository = "qu1x/kiss3d-trackball" }

[dependencies]
kiss3d = {git = "https://github.com/Graph-Donte-Crypto/kiss3d"}
nalgebra = "0.26"
trackball = {git = "https://github.com/Graph-Donte-Crypto/trackball"}

[features]
cc = ["trackball/cc"]
